export DISTRO=buster
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias cdnut='cd "/data/home/jimmy/nutstore/我的坚果云"'
alias cddown='cd "/home/jimmy/Downloads"'
alias cdplay='cd "/home/jimmy/playpen"'
alias cdbot='cd "/home/jimmy/playpen/tradebot"'
alias cdlog='cd "/home/jimmy/tmp/log"'
alias lhwc='lftp -e "cd ~/playpen/tradebot" -u ak, sftp://hwc'
alias lj2='lftp -e "cd ~/playpen/tradebot" -u ubuntu, sftp://jaora2'
alias lj='lftp -e "cd ~/playpen/tradebot" -u opc, sftp://jaora'
alias lru='lftp -e "cd ~/playpen/tradebot" -u ak, sftp://ru-just'
alias lali='lftp -e "cd ~/playpen/tradebot" -u ak, sftp://ali'
alias lus='lftp -e "cd ~/playpen/tradebot" -u ak, sftp://us-lisa2'
alias ltcvm='lftp -e "cd ~/playpen/tradebot" -u ak, sftp://tcvm'
alias lfree='lftp -u ak, sftp://freeshell'
alias time='/usr/bin/time -f "%E"'
alias umatrix='/usr/local/bin/unimatrix -a -c red -f -l aAcCkns -s 97'
alias cmatrix='/usr/local/bin/cmatrix -ab -C blue'

#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PATH:."
