# Reference:
# https://www.codependentcodr.com/using-starship-for-terminal-prompt-goodness.html

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format is currently supported for the following shells: elvish, fish, zsh, xonsh, cmd, nushell.
# right_format = """$all"""

# format = "$all$line_break$directory$line_break$character"

# format = "$directory$line_break$all$line_break$character"
# or
#format = """
#$directory\
#$line_break\
#$all\
#$line_break\
#$character
#"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = false
style = "yellow"
#format = "in [$path]($style)[$read_only]($read_only_style) "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "bold blue"
format = '[\($symbol$branch\)]($style) '

[custom.tztime]
#command = 'date +"%Y-%m-%d%A%l:%M%p(%Z%z)"'
command = 'date +"%Y-%m-%d %H:%M:%S %A (%Z%:::z)"'
when = "true"
format = '[\[$symbol($output)\]](green) '

[custom.uptime]
command = "uptime.sh"
when = "true"
format = "[$symbol($output)](green) "
